<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Cross-platform library: Windows, Linux, macOS and (in the future) Android -->
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EmuSync.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.68.0.3601" />
  </ItemGroup>

</Project>
